version: "3.9"
services:
  redis:
    image: "redis:alpine"
    container_name: "redis_server"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - basic-training-network

volumes:
  redis_data:

networks:
  basic-training-network:
    driver: bridge
